name: Lighthouse CI for URL and Slack Notification

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: '0 12 * * *' # Runs daily at 12:00 UTC

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Lighthouse against URL
        run: |
          REPORT_PATH=$(mktemp -d)/lighthouse.report.json
          npm i -g @lhci/cli
          lhci collect --url=https://briebug.com --output-path=$REPORT_PATH
          lhci upload --target=$REPORT_PATH
          echo "REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV

      - name: Extract Lighthouse Scores
        id: extract_scores
        run: |
          export PERFORMANCE=$(jq '.categories.performance.score * 100' ${{ env.REPORT_PATH }})
          export ACCESSIBILITY=$(jq '.categories.accessibility.score * 100' ${{ env.REPORT_PATH }})
          export BEST_PRACTICES=$(jq '.categories."best-practices".score * 100' ${{ env.REPORT_PATH }})
          export SEO=$(jq '.categories.seo.score * 100' ${{ env.REPORT_PATH }})
          echo "PERFORMANCE=$PERFORMANCE" >> $GITHUB_ENV
          echo "ACCESSIBILITY=$ACCESSIBILITY" >> $GITHUB_ENV
          echo "BEST_PRACTICES=$BEST_PRACTICES" >> $GITHUB_ENV
          echo "SEO=$SEO" >> $GITHUB_ENV

      - name: Post to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PERFORMANCE: ${{ env.PERFORMANCE }}
          ACCESSIBILITY: ${{ env.ACCESSIBILITY }}
          BEST_PRACTICES: ${{ env.BEST_PRACTICES }}
          SEO: ${{ env.SEO }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"Lighthouse Report for https://your-url.com:\nPerformance: $PERFORMANCE\nAccessibility: $ACCESSIBILITY\nBest Practices: $BEST_PRACTICES\nSEO: $SEO\"
          }" $SLACK_WEBHOOK_URL
