name: Lighthouse CI for URL and Slack Notification

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Runs Monday through Friday at 4:00 PM UTC (9:00 AM MT Standard Time)
    - cron: '0 16 * * 1-5'

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Lighthouse against URL
        run: |
          REPORT_PATH=$(mktemp -d)
          npm i -g @lhci/cli
          echo "REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV
          echo "Report Path: $REPORT_PATH"
          lhci collect --url=https://briebug.com
          lhci upload --target=filesystem --outputDir="$REPORT_PATH"

      - name: List files and manifest in lighthouse-report directory
        run: |
          jq '.' $REPORT_PATH/manifest.json | jq

      - name: Extract Lighthouse Scores
        id: extract_scores
        run: |
          representative_run=$(jq '.[] | select(.isRepresentativeRun) | .summary' $REPORT_PATH/manifest.json)
          
          export PERFORMANCE=$(echo "$representative_run" | jq -r '.performance * 100')
          export ACCESSIBILITY=$(echo "$representative_run" | jq -r '.accessibility * 100')
          export BEST_PRACTICES=$(echo "$representative_run" | jq -r '.["best-practices"] * 100')
          export SEO=$(echo "$representative_run" | jq -r '.seo * 100')
        
          echo "PERFORMANCE=$PERFORMANCE" >> $GITHUB_ENV
          echo "ACCESSIBILITY=$ACCESSIBILITY" >> $GITHUB_ENV
          echo "BEST_PRACTICES=$BEST_PRACTICES" >> $GITHUB_ENV
          echo "SEO=$SEO" >> $GITHUB_ENV

      - name: Post to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PERFORMANCE: ${{ env.PERFORMANCE }}
          ACCESSIBILITY: ${{ env.ACCESSIBILITY }}
          BEST_PRACTICES: ${{ env.BEST_PRACTICES }}
          SEO: ${{ env.SEO }}
        run: |
          current_date=$(date +"%m/%d/%Y")
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"Lighthouse Report for https://briebug.com on $current_date\nPerformance: $PERFORMANCE\nAccessibility: $ACCESSIBILITY\nBest Practices: $BEST_PRACTICES\nSEO: $SEO\"
          }" $SLACK_WEBHOOK_URL

